name: android_keychain_flutter
description: "A Flutter plugin for generating attested key pairs using Android's KeyStore."
version: 1.0.6
publish_to: 'none'


environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: android.keychain.flutter
        pluginClass: AndroidKeychainFlutterPlugin
